// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEaEEwqC9Hnak5_gGwU5j3TmAA7fjJZM',
    appId: '1:70356644075:android:c142fdc912fa13d33cceae',
    messagingSenderId: '70356644075',
    projectId: 'petshop-pex',
    storageBucket: 'petshop-pex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8dsiZEIkI0UtHiyj7n2AkPQDkgywqT1g',
    appId: '1:70356644075:ios:0e9a19267d8b499c3cceae',
    messagingSenderId: '70356644075',
    projectId: 'petshop-pex',
    storageBucket: 'petshop-pex.firebasestorage.app',
    iosBundleId: 'com.example.petshopPex',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZKPiQlKQ5F9xp_LIUxwST_frzHASJ9os',
    appId: '1:70356644075:web:1951afb1d9488be53cceae',
    messagingSenderId: '70356644075',
    projectId: 'petshop-pex',
    authDomain: 'petshop-pex.firebaseapp.com',
    storageBucket: 'petshop-pex.firebasestorage.app',
    measurementId: 'G-N3GKTF86MW',
  );

}